enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Strava]
build-mode = "apk"
apkmirror-dlurl = "https://apkpure.com/strava-run-hike-android-exercise-laugh/com.strava"
uptodown-dlurl = "https://strava.en.uptodown.com/android"
patches-source = "ReVanced/revanced-patches"
cli-source = "ReVanced/revanced-cli"
rv-brand = "RV"

[StravaBeta]
build-mode = "apk"
apkmirror-dlurl = "https://apkpure.com/strava-run-hike-android-exercise-laugh/com.strava"
uptodown-dlurl = "https://strava.en.uptodown.com/android"
patches-source = "ReVanced/revanced-patches"
cli-source = "ReVanced/revanced-cli"
rv-brand = "RV"
version = "beta"

[musicBeta]
enabled = false
build-mode = "apk"
apkmirror-dlurl = "https://apkpure.com/strava-run-hike-android-exercise-laugh/com.strava"
uptodown-dlurl = "https://strava.en.uptodown.com/android"
version = "beta"
patches-source = "ReVanced/revanced-patches"
cli-source = "ReVanced/revanced-cli"
rv-brand = "RV"
